### ISSUE TITLE
`ModuleNotFoundError` running chat-with-mlx, `huggingface_hub.utils._errors` not found

### ISSUE THREAD

**Issue by bdruth** [qnguyen3/chat-with-mlx#247]
With PIP install or Conda install, same error:

```
❯ chat-with-mlx
Traceback (most recent call last):
  File "/Users/bdruth/radioconda/envs/mlx-chat/bin/chat-with-mlx", line 5, in <module>
    from chat_with_mlx.app import main
  File "/Users/bdruth/Projects/chat-with-mlx/chat_with_mlx/app.py", line 10, in <module>
    from mlx_lm import load, stream_generate, generate
  File "/Users/bdruth/radioconda/envs/mlx-chat/lib/python3.11/site-packages/mlx_lm/__init__.py", line 3, in <module>
    from .utils import convert, generate, load, stream_generate
  File "/Users/bdruth/radioconda/envs/mlx-chat/lib/python3.11/site-packages/mlx_lm/utils.py", line 17, in <module>
    from huggingface_hub.utils._errors import RepositoryNotFoundError
ModuleNotFoundError: No module named 'huggingface_hub.utils._errors'
```

I'm not well-versed in Conda, but trying to manually run `conda install -c conda-forge huggingface_hub`, while completing successfully, doesn't work, either. Same error.

```
❯ python --version
Python 3.11.10
❯ python -c "import sys; print(list(filter(lambda s: s.find('packages') > -1, sys.path)))"
['/Users/bruth/radioconda/envs/mlx-chat/lib/python3.11/site-packages']
❯ conda list | grep hugging
huggingface_hub           0.25.2             pyh0610db2_0    conda-forge
❯ pip list | grep hugging
huggingface_hub                          0.25.2
```

fwiw, on macOS Sequoia (15.0.1), with default python 3.10.13, just doing a `pip install chat-with-mlx` (easy mode) succeeds but also fails in the same way as above.

Cheers! Happy to help with any further debugging.

**Comment by bdruth** [comment]
https://github.com/ml-explore/mlx-examples/issues/994 suggests running `pip install -U mlx-lm` which runs with an ominous warning/error at the end, but it does push mlx-lm to version 0.19.0, and running `chat-with-mlx` succeeds.

**Comment by bdruth** [comment]
Even with this, I wasn't able to get anything to work - connection error trying to download any model. Errors in the console indicated something w/ pydantic. I had this even from downgrading mlx-lm `huggingface-hub==0.24.7`

**Comment by kriebe** [comment]
Had the same issue.  I'm on an M1 Mac with Sonoma 14.5.  I originally tried it in Pinokio and go this error, so I figured I'd try a manual install and got the same.

**Comment by davideuler** [comment]
Upgrade gradio to 4.44.1: pip install gradio==4.44.1, and the configuration of yaml file like this:

```
original_repo: qwen/Qwen2.5-Coder-32B-Instruct-16bit # The original HuggingFace Repo, this helps with displaying
mlx-repo: mlx-community/Qwen2.5-Coder-32B-Instruct-16bit # The MLX models Repo, most are available through `mlx-community`
#quantize: 8bit # Optional: [4bit, 8bit]
default_language: multi # Optional: [en, es, zh, vi, multi]
```

It support 16bit unquantized mlx model.  It works on my mac sillicon.

**Comment by leo4life2** [comment]
same.
