### ISSUE TITLE
Time out

### ISSUE THREAD

**Issue by TruongNguyenYenNhi** [qnguyen3/chat-with-mlx#35]
You try to use a model that was created with version 2.4.0.dev0, however, your version is 2.4.0. This might cause unexpected behavior or errors. In that case, try to update to the latest version.

<All keys matched successfully>
/workspace/user/miniconda3/envs/mlx-chat/lib/python3.11/site-packages/torch/cuda/__init__.py:141: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 11040). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:108.)
  return torch._C._cuda_getDeviceCount() > 0
Traceback (most recent call last):
  File "/workspace/user/miniconda3/envs/mlx-chat/lib/python3.11/site-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
    yield
  File "/workspace/user/miniconda3/envs/mlx-chat/lib/python3.11/site-packages/httpx/_transports/default.py", line 113, in __iter__
    for part in self._httpcore_stream:
  File "/workspace/user/miniconda3/envs/mlx-chat/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 367, in __iter__
    raise exc from None
  File "/workspace/user/miniconda3/envs/mlx-chat/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 363, in __iter__
    for part in self._stream:
  File "/workspace/user/miniconda3/envs/mlx-chat/lib/python3.11/site-packages/httpcore/_sync/http11.py", line 349, in __iter__
    raise exc
  File "/workspace/user/miniconda3/envs/mlx-chat/lib/python3.11/site-packages/httpcore/_sync/http11.py", line 341, in __iter__
    for chunk in self._connection._receive_response_body(**kwargs):
  File "/workspace/user/miniconda3/envs/mlx-chat/lib/python3.11/site-packages/httpcore/_sync/http11.py", line 210, in _receive_response_body
    event = self._receive_event(timeout=timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/user/miniconda3/envs/mlx-chat/lib/python3.11/site-packages/httpcore/_sync/http11.py", line 224, in _receive_event
    data = self._network_stream.read(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/user/miniconda3/envs/mlx-chat/lib/python3.11/site-packages/httpcore/_backends/sync.py", line 124, in read
    with map_exceptions(exc_map):
  File "/workspace/user/miniconda3/envs/mlx-chat/lib/python3.11/contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/workspace/user/miniconda3/envs/mlx-chat/lib/python3.11/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ReadTimeout: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/workspace/user/miniconda3/envs/mlx-chat/lib/python3.11/site-packages/gradio/queueing.py", line 495, in call_prediction
    output = await route_utils.call_process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/user/miniconda3/envs/mlx-chat/lib/python3.11/site-packages/gradio/route_utils.py", line 233, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/user/miniconda3/envs/mlx-chat/lib/python3.11/site-packages/gradio/blocks.py", line 1608, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/user/miniconda3/envs/mlx-chat/lib/python3.11/site-packages/gradio/blocks.py", line 1188, in call_function
    prediction = await utils.async_iteration(iterator)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/user/miniconda3/envs/mlx-chat/lib/python3.11/site-packages/gradio/utils.py", line 513, in async_iteration
    return await iterator.__anext__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/user/miniconda3/envs/mlx-chat/lib/python3.11/site-packages/gradio/utils.py", line 639, in asyncgen_wrapper
    response = await iterator.__anext__()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/user/miniconda3/envs/mlx-chat/lib/python3.11/site-packages/gradio/chat_interface.py", line 487, in _stream_fn
    first_response = await async_iteration(generator)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/user/miniconda3/envs/mlx-chat/lib/python3.11/site-packages/gradio/utils.py", line 513, in async_iteration
    return await iterator.__anext__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/user/miniconda3/envs/mlx-chat/lib/python3.11/site-packages/gradio/utils.py", line 506, in __anext__
    return await anyio.to_thread.run_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/user/miniconda3/envs/mlx-chat/lib/python3.11/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/user/miniconda3/envs/mlx-chat/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/workspace/user/miniconda3/envs/mlx-chat/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/user/miniconda3/envs/mlx-chat/lib/python3.11/site-packages/gradio/utils.py", line 489, in run_sync_iterator_async
    return next(iterator)
           ^^^^^^^^^^^^^^
  File "/workspace/user/projects/chat-with-mlx/app.py", line 173, in chatbot
    for chunk in response:
  File "/workspace/user/miniconda3/envs/mlx-chat/lib/python3.11/site-packages/openai/_streaming.py", line 44, in __iter__
    for item in self._iterator:
  File "/workspace/user/miniconda3/envs/mlx-chat/lib/python3.11/site-packages/openai/_streaming.py", line 56, in __stream__
    for sse in iterator:
  File "/workspace/user/miniconda3/envs/mlx-chat/lib/python3.11/site-packages/openai/_streaming.py", line 48, in _iter_events
    yield from self._decoder.iter(self.response.iter_lines())
  File "/workspace/user/miniconda3/envs/mlx-chat/lib/python3.11/site-packages/openai/_streaming.py", line 224, in iter
    for line in iterator:
  File "/workspace/user/miniconda3/envs/mlx-chat/lib/python3.11/site-packages/httpx/_models.py", line 861, in iter_lines
    for text in self.iter_text():
  File "/workspace/user/miniconda3/envs/mlx-chat/lib/python3.11/site-packages/httpx/_models.py", line 848, in iter_text
    for byte_content in self.iter_bytes():
  File "/workspace/user/miniconda3/envs/mlx-chat/lib/python3.11/site-packages/httpx/_models.py", line 829, in iter_bytes
    for raw_bytes in self.iter_raw():
  File "/workspace/user/miniconda3/envs/mlx-chat/lib/python3.11/site-packages/httpx/_models.py", line 883, in iter_raw
    for raw_stream_bytes in self.stream:
  File "/workspace/user/miniconda3/envs/mlx-chat/lib/python3.11/site-packages/httpx/_client.py", line 126, in __iter__
    for chunk in self._stream:
  File "/workspace/user/miniconda3/envs/mlx-chat/lib/python3.11/site-packages/httpx/_transports/default.py", line 112, in __iter__
    with map_httpcore_exceptions():
  File "/workspace/user/miniconda3/envs/mlx-chat/lib/python3.11/contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/workspace/user/miniconda3/envs/mlx-chat/lib/python3.11/site-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ReadTimeout: timed out

**Comment by jiangyang118** [comment]
I have the same problem.

**Comment by qnguyen3** [comment]
Hi, this product is meant for Apple Macbook that are running Apple Silicon chip (M1/M2/M3). I see that you have `CUDA` in there, which is absolutely incompatible with this app. If you are using Nvidia cards, please consider Chat with RTX

**Comment by TruongNguyenYenNhi** [comment]
Thanks

**Comment by jiangyang118** [comment]
> Hi, this product is meant for Apple Macbook that are running Apple Silicon chip (M1/M2/M3). I see that you have `CUDA` in there, which is absolutely incompatible with this app. If you are using Nvidia cards, please consider Chat with RTX

thinks
