### ISSUE TITLE
Error reported when executing ‘chat-with-mlx’ command

### ISSUE THREAD

**Issue by hibisicus** [qnguyen3/chat-with-mlx#87]
OS:macbookpro 2021,Sonoma 14.2.1

ERROR:
```
Traceback (most recent call last):
  File "/Users/hibisicus/miniforge3/lib/python3.8/site-packages/langchain_community/embeddings/huggingface.py", line 59, in __init__
    import sentence_transformers
  File "/Users/hibisicus/miniforge3/lib/python3.8/site-packages/sentence_transformers/__init__.py", line 3, in <module>
    from .datasets import SentencesDataset, ParallelSentencesDataset
  File "/Users/hibisicus/miniforge3/lib/python3.8/site-packages/sentence_transformers/datasets/__init__.py", line 3, in <module>
    from .ParallelSentencesDataset import ParallelSentencesDataset
  File "/Users/hibisicus/miniforge3/lib/python3.8/site-packages/sentence_transformers/datasets/ParallelSentencesDataset.py", line 4, in <module>
    from .. import SentenceTransformer
  File "/Users/hibisicus/miniforge3/lib/python3.8/site-packages/sentence_transformers/SentenceTransformer.py", line 24, in <module>
    from .evaluation import SentenceEvaluator
  File "/Users/hibisicus/miniforge3/lib/python3.8/site-packages/sentence_transformers/evaluation/__init__.py", line 3, in <module>
    from .BinaryClassificationEvaluator import BinaryClassificationEvaluator
  File "/Users/hibisicus/miniforge3/lib/python3.8/site-packages/sentence_transformers/evaluation/BinaryClassificationEvaluator.py", line 5, in <module>
    from sklearn.metrics.pairwise import paired_cosine_distances, paired_euclidean_distances, paired_manhattan_distances
  File "/Users/hibisicus/miniforge3/lib/python3.8/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/Users/hibisicus/miniforge3/lib/python3.8/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/Users/hibisicus/miniforge3/lib/python3.8/site-packages/sklearn/utils/__init__.py", line 21, in <module>
    from scipy.sparse import issparse
  File "/Users/hibisicus/miniforge3/lib/python3.8/site-packages/scipy/sparse/__init__.py", line 283, in <module>
    from . import csgraph
  File "/Users/hibisicus/miniforge3/lib/python3.8/site-packages/scipy/sparse/csgraph/__init__.py", line 182, in <module>
    from ._laplacian import laplacian
  File "/Users/hibisicus/miniforge3/lib/python3.8/site-packages/scipy/sparse/csgraph/_laplacian.py", line 7, in <module>
    from scipy.sparse.linalg import LinearOperator
  File "/Users/hibisicus/miniforge3/lib/python3.8/site-packages/scipy/sparse/linalg/__init__.py", line 120, in <module>
    from ._isolve import *
  File "/Users/hibisicus/miniforge3/lib/python3.8/site-packages/scipy/sparse/linalg/_isolve/__init__.py", line 4, in <module>
    from .iterative import *
  File "/Users/hibisicus/miniforge3/lib/python3.8/site-packages/scipy/sparse/linalg/_isolve/iterative.py", line 9, in <module>
    from . import _iterative
ImportError: dlopen(/Users/hibisicus/miniforge3/lib/python3.8/site-packages/scipy/sparse/linalg/_isolve/_iterative.cpython-38-darwin.so, 0x0002): Library not loaded: @rpath/liblapack.3.dylib
  Referenced from: <4FB2C529-F29B-3B2A-AA66-BBB0F1340F73> /Users/hibisicus/miniforge3/lib/python3.8/site-packages/scipy/sparse/linalg/_isolve/_iterative.cpython-38-darwin.so
  Reason: tried: '/Users/hibisicus/miniforge3/lib/python3.8/site-packages/scipy/sparse/linalg/_isolve/../../../../../../liblapack.3.dylib' (no such file), '/Users/hibisicus/miniforge3/lib/python3.8/site-packages/scipy/sparse/linalg/_isolve/../../../../../../liblapack.3.dylib' (no such file), '/Users/hibisicus/miniforge3/lib/liblapack.3.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/hibisicus/miniforge3/lib/liblapack.3.dylib' (no such file), '/Users/hibisicus/miniforge3/lib/liblapack.3.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/hibisicus/miniforge3/lib/liblapack.3.dylib' (no such file), '/Users/hibisicus/miniforge3/bin/../lib/liblapack.3.dylib' (no such file), '/Users/hibisicus/miniforge3/lib/liblapack.3.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/hibisicus/miniforge3/lib/liblapack.3.dylib' (no such file), '/Users/hibisicus/miniforge3/lib/liblapack.3.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/hibisicus/miniforge3/lib/liblapack.3.dylib' (no such file), '/Users/hibisicus/miniforge3/bin/../lib/liblapack.3.dylib' (no such file), '/usr/local/lib/liblapack.3.dylib' (no such file), '/usr/lib/liblapack.3.dylib' (no such file, not in dyld cache)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/hibisicus/miniforge3/bin/chat-with-mlx", line 5, in <module>
    from chat_with_mlx.app import main
  File "/Users/hibisicus/miniforge3/lib/python3.8/site-packages/chat_with_mlx/app.py", line 26, in <module>
    emb = HuggingFaceEmbeddings(model_name='nomic-ai/nomic-embed-text-v1.5', model_kwargs={'trust_remote_code':True})
  File "/Users/hibisicus/miniforge3/lib/python3.8/site-packages/langchain_community/embeddings/huggingface.py", line 62, in __init__
    raise ImportError(
ImportError: Could not import sentence_transformers python package. Please install it with `pip install sentence-transformers`.
```
——————————————————————————————————————
i try ' pip3 install --upgrade pip'、'pip3 install torch'、‘pip3 install transformers==4.7.0’，The error still exists。
May I ask how to solve it？

**Comment by hibisicus** [comment]
```
pip3 install --pre torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/nightly/cpu

```
this command can resolve the error
